# Python circleci config file

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys: 
             - v2-dependencies-{{ checksum "requirements.txt" }}
             - v2-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
      - run:
            name: run lint
            command: |
              . venv/bin/activate 
              make lint
